### ISSUE TITLE
Link zur Korrektur eines spezifischen Datenpunkts erlauben

### ISSUE THREAD

**Issue by silberzwiebel** [codeformuenster/verkehrsunfaelle-editor#10]
Jeder Marker auf crashes bekommt einen solchen Link, sodass eine evtl. falsche Lokalisierung schnell korrigiert werden kann.

**Comment by ubergesundheit** [comment]
Möglich seit eb12f3e93bfc4c78cf9bc27036776e0ccffc16b2
