### ISSUE TITLE
Labels der Buttons anpassen

### ISSUE THREAD

**Issue by ubergesundheit** [codeformuenster/verkehrsunfaelle-editor#15]
Das Label des Buttons "Unfall speichern" wie folgt ändern:

- Initiale Position: "Position korrekt"
- Änderung vorgenommen vom User: "Änderung speichern"

Das Label des Buttons "Nächster Unfall" wie folgt ändern:

- "Ort falsch"
- Klicks als "Unfallort nicht valide" in der Datenbank speichern.

@silberzwiebel @thunfischtoast  @quassy habt ihr bessere Ideen für die Buttonlabels?

**Comment by thunfischtoast** [comment]
Würde den "Nächster Unfall" so lassen, damit man auch ohne Entscheidung skippen kann.
Doch einen dritten Button?

**Comment by ubergesundheit** [comment]
Ein dritter Button passt auf schmalen Displays leider nicht mehr hin bzw würde Platz von der Karte abknapsen. Prinzipiell ist der dritte Button natürlich die sauberste Lösung, wäre mir wohl aber lieb, wenn wir eine Lösung ohne dritten Button hinkriegen könnten.

**Comment by silberzwiebel** [comment]
Finde die Änderung des einen Buttons zu "Ort/Position korrekt" bzw. "Änderungen speichern" bei Nutzeränderung gut.
Für den anderen Button vielleicht einen Text wie "Ort nicht bestimmbar"? Ein rein falscher Ort ist ja uninteressant für uns, der sollte ja gerade gefixt werden. Interessant dann schon eher, wenn die Daten nicht zum Ort bestimmen ausreichen, oder? Wäre für mich auch der einzige Grund, zum nächsten Unfall zu skippen, wenn ich den Ort nicht rausfinden kann.

**Comment by ubergesundheit** [comment]
Finde "Ort nicht bestimmbar" eine gute Idee. Vielleicht lässt sich der dritte Button (in diesem Fall dann "nächster Unfall ohne Aktion") einfach ohne Label in irgendeine Ecke oder so noch quetschen.

**Comment by ubergesundheit** [comment]
Seit https://github.com/codeformuenster/verkehrsunfaelle-editor/commit/8321b1b486b05c3729012f32fee69e01d9b9ffb1 sind nun die Buttons so geändert wie oben besprochen.
