### ISSUE TITLE
Klick auf "Wieso" führt nicht direkt zur Antwort

### ISSUE THREAD

**Issue by silberzwiebel** [codeformuenster/verkehrsunfaelle-editor#16]
Der Link ist zwar korrekt: https://ms-verkehrsunfaelle-beta.netlify.com/faq#wieso-einloggen
Er funktioniert aber nicht mit einem Klick, sondern erst, wenn man die FAQ-Seite nochmal neu lädt.

**Comment by ubergesundheit** [comment]
https://github.com/codeformuenster/verkehrsunfaelle-editor/commit/6af9d0610cf09f2ec9a03543fd6c07f6125afe97 

Bitte einmal checken (bei mir gehts) und schließen. Danke!

**Comment by silberzwiebel** [comment]
Funktioniert, danke!
