### ISSUE TITLE
Tileserver allgemein verständlich benennen & Auswahl reduzieren

### ISSUE THREAD

**Issue by quassy** [codeformuenster/verkehrsunfaelle-editor#17]
Ich denke die aktuelle Auflistung überfordert normale Nutzer bzw. kann von diesem kaum nachvollzogen werden. 

Statt: 
* OpenTopoMap
* OpenStreetMap
* DOP 2018
* DOP 2014
* DOP 2011
* DOP 2008

Würde ich vorschlagen:
* Topografie
* Stadtplan
* Luftbild (das Jahr wird automatisch entsprechend des Unfallzeitpunkts gewählt)

_(Ich persönlich würde auch OSM als default bevorzugen, da die Daten aktueller und detaillierter zu sein scheinen. Beziehungsweise bin ich mir nicht sicher, ob die Topokarte überhaupt notwendig ist. Das wäre aber sein separates Issue.)_

**Comment by ubergesundheit** [comment]
Guter Punkt!
