### ISSUE TITLE
auf Suche prominenter hinweisen

### ISSUE THREAD

**Issue by silberzwiebel** [codeformuenster/verkehrsunfaelle-editor#21]
Bei einem Unfall ohne Geokodierung einen Satz hinzufügen, der auf die Möglichkeit der Suche links hinweist.

**Comment by ubergesundheit** [comment]
Habe in https://github.com/codeformuenster/verkehrsunfaelle-editor/commit/9da316214e754b8b223b018eccb0d084d46fc400 folgendes dazugebaut: Im Overlay gibt es nun einen klickbaren Text, der a) die Suche öffnet b) eine Suche ausführt c) den Overlay versteckt.

Hast du noch Verbesserungsvorschläge?

**Comment by silberzwiebel** [comment]
Sieht super aus, danke!

**Comment by silberzwiebel** [comment]
Gerne noch prominenter: Statt "Marker platzieren" standardmäßig Suche öffnen. Sonst muss man Texte durchlesen, und das tun nicht alle, um die Suche zu finden.

**Comment by ubergesundheit** [comment]
b8d04968f5f8e3ec479121a53f1b5b1cf3a8d2df
