### ISSUE TITLE
mehr Infos pro Unfall auf Korrekturseite

### ISSUE THREAD

**Issue by silberzwiebel** [codeformuenster/verkehrsunfaelle-editor#24]
Basierend auf meinem Test gerade fände ich es gut, wenn folgende Extrainfos für jeden Unfall direkt angezeigt würden

- [ ] Datum des Unfalls (um bei Bedarf das passende Luftbild auswählen zu können)
- [ ] beteiligte Unfallfahrzeuge (für genaue Ortsbestimmung: PKW-Unfall z.B. geht nicht auf reinen Radwegen)

**Comment by ubergesundheit** [comment]
39dc09c4e1869b9a1a876acddd8564a9a56ecda5
