### ISSUE TITLE
Loginsession nicht persistent

### ISSUE THREAD

**Issue by quassy** [codeformuenster/verkehrsunfaelle-editor#29]
Der Login auf der Seite scheint nicht dauerhaft gespeichert zu werden. Öffnet man einen neuen Tab ist man just wieder als "Anonym" eingeloggt und nicht mehr mit dem eigenen Nutzeraccount.

**Comment by ubergesundheit** [comment]
Ist so gewollt. So kommt die Seite ohne Cookies/LocalStorage aus und braucht keinen Cookie-Banner.
